[pre-commit.ci] pre-commit autoupdate (#420)
* [pre-commit.ci] pre-commit autoupdate

updates:
- [github.com/astral-sh/ruff-pre-commit: v0.14.6 → v0.14.8](https://github.com/astral-sh/ruff-pre-commit/compare/v0.14.6...v0.14.8)
- [github.com/psf/black-pre-commit-mirror: 25.11.0 → 25.12.0](https://github.com/psf/black-pre-commit-mirror/compare/25.11.0...25.12.0)
- [github.com/pre-commit/mirrors-mypy: v1.18.2 → v1.19.0](https://github.com/pre-commit/mirrors-mypy/compare/v1.18.2...v1.19.0)

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Adjust for new `untyped-decorator` error code from mypy

* Turns out we need misc for other things:

```
tests/eval_files/exception_suppress_context_manager.py:139: error: Cannot assign to a type  [misc]
tests/eval_files/exception_suppress_context_manager.py:139: note: Error code "misc" not covered by "type: ignore" comment
tests/eval_files/async124.py:87: error: Single overload definition, multiple required  [misc]
tests/eval_files/async104.py:194: error: "return" outside function  [misc]
tests/eval_files/async104.py:198: error: "return" outside function  [misc]
tests/autofix_files/exception_suppress_context_manager.py:152: error: Cannot assign to a type  [misc]
tests/autofix_files/exception_suppress_context_manager.py:152: note: Error code "misc" not covered by "type: ignore" comment
tests/autofix_files/async124.py:96: error: Single overload definition, multiple required  [misc]
flake8_async/visitors/flake8asyncvisitor.py:160: error: Class cannot subclass "CSTTransformer" (has type "Any")  [misc]
flake8_async/visitors/visitor91x.py:237: error: Class cannot subclass "CSTTransformer" (has type "Any")  [misc]
```

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: A5rocks <git@helvetica.moe>