Turns out we need misc for other things:
```
tests/eval_files/exception_suppress_context_manager.py:139: error: Cannot assign to a type  [misc]
tests/eval_files/exception_suppress_context_manager.py:139: note: Error code "misc" not covered by "type: ignore" comment
tests/eval_files/async124.py:87: error: Single overload definition, multiple required  [misc]
tests/eval_files/async104.py:194: error: "return" outside function  [misc]
tests/eval_files/async104.py:198: error: "return" outside function  [misc]
tests/autofix_files/exception_suppress_context_manager.py:152: error: Cannot assign to a type  [misc]
tests/autofix_files/exception_suppress_context_manager.py:152: note: Error code "misc" not covered by "type: ignore" comment
tests/autofix_files/async124.py:96: error: Single overload definition, multiple required  [misc]
flake8_async/visitors/flake8asyncvisitor.py:160: error: Class cannot subclass "CSTTransformer" (has type "Any")  [misc]
flake8_async/visitors/visitor91x.py:237: error: Class cannot subclass "CSTTransformer" (has type "Any")  [misc]
```